version: "3.6"

services:
  nginx-futurepynk:
    restart: always
    container_name: nginx-futurepynk
    build: .
    environment:
    env_file: .env.gcp

networks:
  default:
    name: network-futurepynk

      
